### ISSUE TITLE
Cannot load local diffusers model

### ISSUE THREAD

**Issue by LaikaSa** [smy20011/dreambooth-gui#32]
I converted a custom .ckpt model to diffusers. Then clicked on the choose local model and selected folder, but it won't register, and the path in the GUI stays completely blank. When manually copy-pasted the directory to the model and train, it throw me this error: 

Traceback (most recent call last):
  File "/train_dreambooth.py", line 695, in <module>
    main()
  File "/train_dreambooth.py", line 423, in main
    tokenizer = CLIPTokenizer.from_pretrained(args.pretrained_model_name_or_path, subfolder="tokenizer", use_auth_token=True)
  File "/opt/conda/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1748, in from_pretrained
    _commit_hash=commit_hash,
  File "/opt/conda/lib/python3.7/site-packages/transformers/utils/hub.py", line 420, in cached_file
    local_files_only=local_files_only,
  File "/opt/conda/lib/python3.7/site-packages/huggingface_hub/file_download.py", line 1022, in hf_hub_download
    cache_dir, repo_folder_name(repo_id=repo_id, repo_type=repo_type)
  File "/opt/conda/lib/python3.7/site-packages/huggingface_hub/utils/_validators.py", line 92, in _inner_fn
    validate_repo_id(arg_value)
  File "/opt/conda/lib/python3.7/site-packages/huggingface_hub/utils/_validators.py", line 143, in validate_repo_id
    "Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are"
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'E:\Stable\DB GUI\WDCKPT'.

**Comment by LaikaSa** [comment]
This is the training command:
![Untitled12341](https://user-images.githubusercontent.com/112873279/199535403-c3b59517-0945-4790-a1c5-1f0d9242bb5a.png)
