### ISSUE TITLE
Progress bar? Output expectation?

### ISSUE THREAD

**Issue by Duemellon** [smy20011/dreambooth-gui#4]
Is there a progress bar or something that can tell me how it's going? I told it to train & it took less than 1 minute before it appears to have stalled. The [STOP] button is still there but what should I expect as a result or completion verification? 

Where does the CKPT get created/filed?

**Comment by rydogjones** [comment]
Same here...get this: Then just hangs...no clue what it's doing...if anything....
Unable to find image 'smy20011/dreambooth:latest' locally
latest: Pulling from smy20011/dreambooth
40dd5be53814: Already exists
0645c48e225b: Already exists
8889d023c18e: Already exists
74115353f57d: Already exists
9e0ea72fe76c: Already exists
13f51f3f80fd: Pulling fs layer
c4ba9103d17d: Pulling fs layer
8d9b8d71f868: Pulling fs layer
97badaa6a776: Pulling fs layer
63041bc7286a: Pulling fs layer
5f237510596a: Pulling fs layer
e84ba40a3ba2: Pulling fs layer
3514d699b3b1: Pulling fs layer
389cef77d3f2: Pulling fs layer
454b4e6dabd9: Pulling fs layer
08c0b6423a55: Pulling fs layer
08c0b6423a55: Waiting
c4ba9103d17d: Download complete
97badaa6a776: Download complete
5f237510596a: Waiting
389cef77d3f2: Waiting
e84ba40a3ba2: Waiting
3514d699b3b1: Waiting
454b4e6dabd9: Waiting

**Comment by smy20011** [comment]
I think the first run is slower because you need to full all the docker image. Wait after it finished pulling and rerun it should give you correct result.

**Comment by rydogjones** [comment]
Awesome! Thank you so much! Waiting...
Just curious...Why does it need a huggingface token? What is communicating with them for?

**Comment by smy20011** [comment]
You need that token to download model from huggingface website.

**Comment by rydogjones** [comment]
But If I already have the model locally...
can't I just reference it like this /SDModel/sd-v1-4.ckpt in the Model Text box?
My input vars are this:
docker run -t --gpus=all -v=D:\Users\ryanp\Dream\Train:/instance -v=C:\Users\ryanp\AppData\Roaming\smy20011.dreambooth\Mariejones:/class -v=D:\DreamBooth\Output:/output -v=/SDModel/sd-v1-4.ckpt:/input_model -v=C:\Users\ryanp\AppData\Roaming\smy20011.dreambooth\:/train -e HUGGING_FACE_HUB_TOKEN=XXXXXXXXXXXXXXXXXX smy20011/dreambooth:latest /start_training /train_dreambooth.py --pretrained_model_name_or_path=/input_model --instance_prompt=sks --instance_data_dir=/instance --class_data_dir=/class --with_prior_preservation --prior_loss_weight=1.0 --class_prompt=Mariejones --max_train_steps=600 --learning_rate=1e-5 --lr_scheduler=constant --lr_warmup_steps=0 --resolution=512 --output_dir=/output --use_8bit_adam --mixed_precision=fp16 --train_batch_size=1 --gradient_accumulation_steps=1 --use_8bit_adam --resolution=512 --gradient_checkpointing --train_text_encoder

Errors i'm getting now are 
Traceback (most recent call last):
  File "/train_dreambooth.py", line 695, in <module>
    main()
  File "/train_dreambooth.py", line 376, in main
    args.pretrained_model_name_or_path, torch_dtype=torch_dtype, use_auth_token=True
  File "/opt/conda/lib/python3.7/site-packages/diffusers/pipeline_utils.py", line 372, in from_pretrained
    revision=revision,
  File "/opt/conda/lib/python3.7/site-packages/diffusers/configuration_utils.py", line 279, in get_config_dict
    raise EnvironmentError(f"It looks like the config file at '{config_file}' is not a valid JSON file.")
OSError: It looks like the config file at '/input_model' is not a valid JSON file.
I'm guessing that text field is not expecting the MODEL but a JSON config file about a model?
Any docs on the expected values for the various inputs?

**Comment by rydogjones** [comment]
Ahhh I see
 Allow advanced customization
 Load local model.

Local is part of the road map...
So I updated it for get it from hugginface and it seems to be working....at least it's downloading...

**Comment by rydogjones** [comment]
Hey BTW got it all working...yeah it just had to download the model and other stuff.  Works GREAT now. With people I don't even use a CLASS...just leave it blank and it still works great....DID have to change the SKS classname to t@y as SKS is a gun and I kept getting GUN images...

Would love to try to take the OUTPUT Model.ckpt and put it back IN to add another instance image...but can't seem to find where to put it...Is this even possible? Does the downloaded model come down as a ckpt file or is it more complicated than that?

If it's compenents that are coming down from hugginface....is it possible to take the OUTPUT model.ckpt and break it up into the components?  Sorry for stupid questions...just very new at this and fumbling around.
