### ISSUE TITLE
Failed to convert model: "CUDA error: unknown error"

### ISSUE THREAD

**Issue by amenonegames** [smy20011/dreambooth-gui#48]
**Describe the bug**
Error occured!
Always training is failed.

If I checked "Generete model checkpoint" , Error message popup showing "Failed to convert model".
If not, No error pop uped. But There are only logs in output folder...
As both situation, training output is following 

```
Fetching 16 files:   0%|          | 0/16 [00:00<?, ?it/s]
Fetching 16 files: 100%|██████████| 16/16 [00:00<00:00, 172.14it/s]
The config attributes {'feature_extractor': ['transformers', 'CLIPFeatureExtractor'], 'safety_checker': ['stable_diffusion', 'StableDiffusionSafetyChecker']} were passed to StableDiffusionPipeline, but are not expected and will be ignored. Please verify your model_index.json configuration file.
The config attributes {'clip_sample': False} were passed to PNDMScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.
Traceback (most recent call last):
  File "/train_dreambooth.py", line 695, in <module>
    main()
  File "/train_dreambooth.py", line 387, in main
    pipeline.to(accelerator.device)
  File "/opt/conda/lib/python3.7/site-packages/diffusers/pipeline_utils.py", line 198, in to
    module.to(torch_device)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 927, in to
    return self._apply(convert)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 602, in _apply
    param_applied = fn(param)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

****
 - OS: Windows10
 - NVIDIA GeForce RTX 3060 Laptop GPU
 - dreambooth-gui_0.1.8_x64_en-US

**Comment by 10001001011010111010** [comment]
I guess I just face a similar issue.
![cuda_error](https://user-images.githubusercontent.com/41110249/200173249-8e3b4748-817c-4443-89b5-4715b7c6e299.JPG)

**Comment by 10001001011010111010** [comment]
> I guess I just face a similar issue (1080Ti) - will update Nvidia drivers / CUDA next.

Updated driver and installed CUDA Toolkit 11.8 

Fetching 16 files:   0%|          | 0/16 [00:00<?, ?it/s]
Fetching 16 files: 100%|██████████| 16/16 [00:00<00:00, 171.31it/s]
The config attributes {'feature_extractor': ['transformers', 'CLIPFeatureExtractor'], 'safety_checker': ['stable_diffusion', 'StableDiffusionSafetyChecker']} were passed to StableDiffusionPipeline, but are not expected and will be ignored. Please verify your model_index.json configuration file.
The config attributes {'clip_sample': False} were passed to PNDMScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.

Generating class images:   0%|          | 0/25 [00:00<?, ?it/s]
Generating class images:   0%|          | 0/25 [05:01<?, ?it/s]
Traceback (most recent call last):
  File "/train_dreambooth.py", line 695, in <module>
    main()
  File "/train_dreambooth.py", line 393, in main
    images = pipeline(example["prompt"]).images
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 343, in __call__
    image = self.vae.decode(latents).sample
  File "/opt/conda/lib/python3.7/site-packages/diffusers/models/vae.py", line 577, in decode
    dec = self.decoder(z)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/diffusers/models/vae.py", line 217, in forward
    sample = up_block(sample)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/diffusers/models/unet_blocks.py", line 1277, in forward
    hidden_states = resnet(hidden_states, temb=None)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/diffusers/models/resnet.py", line 385, in forward
    hidden_states = self.conv1(hidden_states)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by smy20011** [comment]
It's a wired CUDA error. I have 1080ti as well and use that testing daily. I think I will leave this issue open and see if more bug report coming in.

**Comment by 10001001011010111010** [comment]
“Wired CUDA error”
No idea what that is though but I guess back to collab then… Thanks for your support 👍

**Comment by smy20011** [comment]
Could you do a `docker pull smy20011/dreambooth:latest` in cmd? That may fix the problem.

**Comment by amenonegames** [comment]
Thank you for your investigation!
And I found my fault. My PC's VRAM is only 8GB. Lower than dream booth gui required. I'm sorry.

This error message is displayed when VRAM is short according to this tweet...
( this is japanese tweet )
https://twitter.com/sifue/status/1564365784649850880?s=20&t=xEQtlyHWNbBx-v-CKz-u0Q

If the matter of 10001001011010111010-san is same, Please close this issue.

**Comment by amenonegames** [comment]
*I tryed docker pull smy20011/dreambooth:latest in my cmd, but error was same.  I'm reporting this just in case.

**Comment by 10001001011010111010** [comment]
After "docker pull smy20011/dreambooth:latest" still the same CUDA error. I have a 1080Ti with 11 Gb VRAM.
