### ISSUE TITLE
No module named 'pytorch_lightning'

### ISSUE THREAD

**Issue by Seth-Scott** [smy20011/dreambooth-gui#61]
**Describe the bug**
No module named 'pytorch_lightning'

**To Reproduce**
1. Select `training folder`
2. Input `instance prompt`
3. Input `Hugging Face token`
4. See error:

```python3
Saving to: ‘v1-inference.yaml’


v1-inference.yaml     0%[                    ]       0  --.-KB/s               
v1-inference.yaml   100%[===================>]   1.83K  --.-KB/s    in 0s      

2022-11-10 20:43:25 (35.6 MB/s) - ‘v1-inference.yaml’ saved [1873/1873]

Traceback (most recent call last):
  File "/diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py", line 673, in <module>
    checkpoint = torch.load(args.checkpoint_path)
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 1049, in _load
    result = unpickler.load()
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 1042, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'pytorch_lightning'
```

**Expected behavior**
Training the image as normal

**Desktop:**
 - OS: Win 10 Pro
 - [ dreambooth-gui_0.1.9_x64_en-US.msi ](https://github.com/smy20011/dreambooth-gui/releases/download/v0.1.9/dreambooth-gui_0.1.9_x64_en-US.msi)
 - GPU: Titan X Pascal
 
How would I go about with a workaround for this temporarily?

**Comment by smy20011** [comment]
Thank you for bug report! It seems like a bug for local ckpt training.

I will try to push a new docker image to solve this problem.

**Comment by smy20011** [comment]
New image is updated, do you mind try it again?

**Comment by Seth-Scott** [comment]
Thanks for the quick response. I uninstalled, cleared my existing docker images and reinstalled. After attempting with the same settings, I'm getting the following output:

```console
..... 
4c0bbc1752ce: Pull complete
Digest: sha<XXXX not sure if this is sensitive>
Status: Downloaded newer image for smy20011/dreambooth:v0.1.9
docker: Error response from daemon: invalid mount config for type "bind": stat /run/desktop/mnt/host/c/Users/<me>/OneDrive/Desktop/StableDiffusionWebUI/stable-diffusion-webui/models/Stable-diffusion/1.5_model.ckpt: input/output error.
See 'docker run --help'.
```

**Comment by smy20011** [comment]
Interesting, do you mind share the training command and make sure the one drive file is correctly mounted?
